### ISSUE TITLE
keyboard null error

### ISSUE THREAD

**Issue by charlesmz** [huffSamuel/WinKeyboardHook.WPF#2]
When the form loses focus, it is not the active form, and the program makes an error, which is not a global hook。
The following code errors the null reference exception：
                var eventArgs = new KeyEventArgs(Keyboard.PrimaryDevice,
                                                 Keyboard.PrimaryDevice.ActiveSource,
                                                 keyInfo.time,
                                                 key);

**Comment by charlesmz** [comment]
I just use the demo in the project.
When the form is not the currently active form, pressing the keyboard will cause an error.
Keyboard.PrimaryDevice.ActiveSource is null

**Comment by charlesmz** [comment]
Here is a gif of me using the demo for this project. I launch the application, type in the box, then switch to Notepad and continue typing,Just like you do. But Throw an exception
i use laptop / Notebook keyboard /windows10 17134 zh-TW
![ad](https://user-images.githubusercontent.com/32212601/47776306-0f9cc800-dd2d-11e8-8def-5e8b80c18818.gif)

**Comment by huffSamuel** [comment]
Thanks for the info. I'll set up a test environment with the same settings to see if I can reproduce this issue.

**Comment by huffSamuel** [comment]
@charlesmz - I've added some code that short-circuits the keyboard event methods if the active window is not the application using WinKeyboardHook. You can find it on the [fix/null_ref_ouside_app branch](https://github.com/huffSamuel/WinKeyboardHook.WPF/tree/fix/null_ref_outside_app).

**Comment by huffSamuel** [comment]
@charlesmz - Checking in again to see if you've been able to replicate the issues with the new fix. I'll be closing this issue on November 26 unless other issues pop up.

**Comment by charlesmz** [comment]
Okay，The  program can now work.
